cass:
  image: cassandra
  volumes:
    - ./tmp/var/lib/cassandra/:/var/lib/cassandra/
  ports:
    - 9042


usergrid:
  image: usergrid
  ports:
    - 8080:8080
  links:
    - cass:cass

test:
  build: test
  links:
    - usergrid
